### ISSUE TITLE
Module drops the Authorization header

### ISSUE THREAD

**Issue by toporchillo** [follow-redirects/follow-redirects#174]
Follow-redirect module drops Authorization header when redirects from site.com to www.site.com. So, it's impossible to get www.site.com page even if you send Authorization headers to site.com.

**Comment by RubenVerborgh** [comment]
Thanks, solved by https://github.com/follow-redirects/follow-redirects/pull/173

**Comment by toporchillo** [comment]
Your fix does not resolve most common case. We need to keep Auth header on redirect from site.com to www.site.com.

**Comment by RubenVerborgh** [comment]
> We need to keep Auth header on redirect from site.com to [www.site.com](http://www.site.com).

It does, here is the test that verifies this behavior:
https://github.com/follow-redirects/follow-redirects/blob/2e1eaf0218c5315a2ab27f53964d0535d4dafb51/test/test.js#L1373-L1382

Please post instructions to reproduce if you think this does not work.
